name: Snake Animation

on:
  schedule:
    # Run every day at midnight
    - cron: "0 0 * * *"

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate Snake
      uses: Platane/snk@v2
      with:
        github_user: coolhango
        svg_out_path: snake.svg

    - name: Commit Snake animation
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add snake.svg
        git commit -m "Generate snake animation"
        git push
